version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - AccountID=$(aws sts get-caller-identity --query Account --output text)
      - CommitID="$(echo $GitCommitID | head -c 8)"
      - Token=$(aws ssm get-parameter --name "/DevTools/microscanner" --with-decryption --query Parameter.Value --output text)
      - echo $Token
      - echo Building the Docker image to Aqua analysis..
      - echo "" >> Dockerfile
      - echo "ADD https://get.aquasec.com/microscanner ." >> Dockerfile
      - echo "RUN chmod +x microscanner" >> Dockerfile
      - echo "RUN ./microscanner $Token --html --continue-on-failure " >> Dockerfile
      - cat Dockerfile
      - docker build --no-cache . >> results.html
      - sed -n '/<html/,/<\/html/p' results.html >> $CommitID.html
      - aws s3 cp $CommitID.html s3://$AccountID-devtools/$ServiceName-$BranchName/$CommitID/container-security-$CommitID.html
      - status=$(grep -wc "continue-on-failure" $CommitID-microscanner.html); if [ $status -eq 0 ]; then exit 0; else exit 1; fi
  post_build:
    commands:
      - echo "Aqua Microscanner Execution Finished..."