version: 0.2

phases:
  install:
    commands:
      - pip install dependency-check
  build:
    commands:
      - AccountID=$(aws sts get-caller-identity --query Account --output text)
      - CommitID="$(echo $GitCommitID | head -c 8)"
      - dependency-check --disableAssembly -s . -o report.html
      - aws s3 cp report.html s3://$AccountID-launcher/$ServiceName-$BranchName/reports/$CommitID-dependency-check.html