version: 0.2

phases:
  install:
    commands:
      - pip install dependency-check
  build:
    commands:
      - AccountID=$(aws sts get-caller-identity --query Account --output text)
      - CommitID="$(echo $GitCommitID | head -c 8)"
      - dependency-check --disableAssembly -s . -o $CommitID.html
      - aws s3 cp $CommitID.html s3://$AccountID-devtools/$ServiceName-$BranchName/$CommitID/dependency-check-$CommitID.html