version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - apt-get install wget apt-transport-https gnupg
      - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
      - echo deb https://aquasecurity.github.io/trivy-repo/deb bionic main | tee -a /etc/apt/sources.list.d/trivy.list
      - apt-get update
      - apt-get install -y trivy
 build:
    commands:
      - docker build -t trivy:test .
  build:
    commands:
      - AccountID=$(aws sts get-caller-identity --query Account --output text)
      - CommitID="$(echo $GitCommitID | head -c 8)"
  post_build:
    commands:
      - trivy --no-progress --exit-code 1 --severity HIGH,CRITICAL trivy:test > report.txt
      - aws s3 cp report.txt s3://$AccountID-devtools/$ServiceName-$BranchName/$CommitID/container-sec-trivy-$CommitID.txt
      - echo "Trivy execution Finished..."